### ISSUE TITLE
What is the meaning of the video name suffix?

### ISSUE THREAD

**Issue by ZhouKanglei** [limuhit/VR-Video-Quality-in-the-Wild#1]
As can be seen from [the video information table](https://github.com/limuhit/VR-Video-Quality-in-the-Wild/blob/main/PCONV/data/video_info.csv), is there a specific semantic meaning of the suffix of video names (such as A, B, etc)?

**Comment by limuhit** [comment]
A and B represent different starting points.
7 and 15 represent different durations.
